# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assistant_final_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1354, 741)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bg1 = QtWidgets.QLabel(self.centralwidget)
        self.bg1.setGeometry(QtCore.QRect(-100, -480, 1621, 1261))
        self.bg1.setText("")
        self.bg1.setPixmap(QtGui.QPixmap("../assistant_material/B.G-20221017T135923Z-001/B.G/Black_Template.jpg"))
        self.bg1.setScaledContents(True)
        self.bg1.setObjectName("bg1")
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(10, 0, 461, 301))
        self.bg_2.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.bg_2.setText("")
        self.bg_2.setScaledContents(True)
        self.bg_2.setObjectName("bg_2")
        self.bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.bg_3.setGeometry(QtCore.QRect(490, 0, 461, 301))
        self.bg_3.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.bg_3.setText("")
        self.bg_3.setScaledContents(True)
        self.bg_3.setObjectName("bg_3")
        self.gif1 = QtWidgets.QLabel(self.centralwidget)
        self.gif1.setGeometry(QtCore.QRect(20, 10, 441, 281))
        self.gif1.setText("")
        self.gif1.setPixmap(QtGui.QPixmap("../assistant_material/ExtraGui-20221017T140106Z-001/Earth.gif"))
        self.gif1.setScaledContents(True)
        self.gif1.setObjectName("gif1")
        self.gif3 = QtWidgets.QLabel(self.centralwidget)
        self.gif3.setGeometry(QtCore.QRect(500, 10, 441, 281))
        self.gif3.setText("")
        self.gif3.setPixmap(QtGui.QPixmap("../assistant_material/VoiceReg-20221017T135923Z-001/VoiceReg/Siri.gif"))
        self.gif3.setScaledContents(True)
        self.gif3.setObjectName("gif3")
        self.text_time = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_time.setGeometry(QtCore.QRect(1070, 580, 241, 71))
        self.text_time.setStyleSheet("background-color: transparent;\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 255, 255);\n"
"border- radius:none;\n"
" ")
        self.text_time.setObjectName("text_time")
        self.text_date = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_date.setGeometry(QtCore.QRect(1070, 490, 241, 71))
        self.text_date.setStyleSheet("background-color: transparent;\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 255, 255);\n"
"border- radius:none;\n"
" ")
        self.text_date.setObjectName("text_date")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1170, 460, 47, 13))
        self.label_2.setObjectName("label_2")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(1110, 330, 151, 51))
        self.pushButton_start.setStyleSheet("background-color: tranparent;\n"
"background-color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 0, 255);\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 255);\n"
"background-radius:none;\n"
"")
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushbutton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushbutton_exit.setGeometry(QtCore.QRect(1110, 400, 151, 51))
        self.pushbutton_exit.setStyleSheet("background-color: tranparent;\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 255);\n"
"background-radius:none;\n"
"")
        self.pushbutton_exit.setObjectName("pushbutton_exit")
        self.pushButton_yt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_yt.setGeometry(QtCore.QRect(510, 320, 141, 51))
        self.pushButton_yt.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 85, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.pushButton_yt.setObjectName("pushButton_yt")
        self.gif3_2 = QtWidgets.QLabel(self.centralwidget)
        self.gif3_2.setGeometry(QtCore.QRect(30, 300, 301, 151))
        self.gif3_2.setText("")
        self.gif3_2.setPixmap(QtGui.QPixmap("../assistant_material/ExtraGui-20221017T140106Z-001/initial.gif"))
        self.gif3_2.setScaledContents(True)
        self.gif3_2.setObjectName("gif3_2")
        self.gif4 = QtWidgets.QLabel(self.centralwidget)
        self.gif4.setGeometry(QtCore.QRect(20, 412, 401, 271))
        self.gif4.setText("")
        self.gif4.setPixmap(QtGui.QPixmap("../assistant_material/gif2.gif"))
        self.gif4.setScaledContents(True)
        self.gif4.setObjectName("gif4")
        self.pushButton_chrome = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_chrome.setGeometry(QtCore.QRect(680, 320, 141, 51))
        self.pushButton_chrome.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 85, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.pushButton_chrome.setObjectName("pushButton_chrome")
        self.gif5 = QtWidgets.QLabel(self.centralwidget)
        self.gif5.setGeometry(QtCore.QRect(460, 402, 501, 271))
        self.gif5.setText("")
        self.gif5.setPixmap(QtGui.QPixmap("../assistant_material/gif3.gif"))
        self.gif5.setScaledContents(True)
        self.gif5.setObjectName("gif5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1200, 290, 47, 13))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1150, 190, 47, 13))
        self.label_3.setObjectName("label_3")
        self.gif6 = QtWidgets.QLabel(self.centralwidget)
        self.gif6.setGeometry(QtCore.QRect(970, 12, 391, 301))
        self.gif6.setText("")
        self.gif6.setPixmap(QtGui.QPixmap("../assistant_material/gif4.gif"))
        self.gif6.setScaledContents(True)
        self.gif6.setObjectName("gif6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1354, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_start.setText(_translate("MainWindow", "START"))
        self.pushbutton_exit.setText(_translate("MainWindow", "EXIT"))
        self.pushButton_yt.setText(_translate("MainWindow", "youtube"))
        self.pushButton_chrome.setText(_translate("MainWindow", "chrome"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
